[package]
name = "jvm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
strum_macros = "0.26.4"
zip = { version = "2.2.0", features = ["deflate"] }
thiserror = "1.0.63"
typed-arena = "2.0.2"
log = "0.4.22"
simple_logger = { version = "5.0.0", features = ["threads"] }
regex = "1.10.6"
lazy-regex = "3.4.1"
cesu8 = "1.1.0"
libloading = "0.8"
libffi = "5.0.0"
serde = { version = "1.0.228", features = ["derive"], optional = true }
nom = "8.0.0"
nom-derive = {path = "../../nom-derive"}
toml = {  version = "0.9.8", optional = true, features = ["serde"]}
parking_lot = "0.12.5"
# consider making jni impls their own crate so libc, libloading and libffi are only a dependency there
# this would mean spliting the vm again to have a lib that can be used by this crate and an implemenation which depends on both
libc = "1.0.0-alpha.3"

[features]
debug = ["dep:toml", "dep:serde"]
il = []
default = ["il"]