[package]
name = "jvm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
strum_macros = "0.26.4"
zip = { version = "2.2.0", features = ["deflate"] }
thiserror = "1.0.63"
typed-arena = "2.0.2"
log = "0.4.22"
simple_logger = { version = "5.0.0", features = ["threads"] }
regex = "1.10.6"
lazy-regex = "3.4.1"
cesu8 = "1.1.0"
libloading = "0.8"
libffi = "5.0.0"
serde = { version = "1.0.228", features = ["derive"], optional = true }
nom = "8.0.0"
nom-derive = {path = "../../nom-derive"}
toml = {  version = "0.9.8", optional = true, features = ["serde"]}

[features]
debug = ["dep:toml", "dep:serde"]
il = []
default = ["il"]